name: Build EasyTier-web

on:
  workflow_dispatch:  # 允许手动触发

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-C target-feature=+crt-static"

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'pnpm'

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable

    - name: Install Linux Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y pkg-config libssl-dev build-essential

    - name: Debug Directory Structure
      run: |
        pwd
        ls -la
        echo "Current directory structure:"
        find . -maxdepth 3 -type d

    - name: Build Frontend-lib
      run: |
        cd easytier-web/frontend-lib
        pnpm install
        pnpm build

    - name: Build Frontend
      run: |
        cd easytier-web/frontend
        pnpm install
        pnpm build

    - name: Build Backend
      run: |
        cd easytier-web
        cargo build --release

    - name: Package Build
      run: |
        cd easytier-web
        mkdir -p release
        cp target/release/easytier-web release/
        cp -r frontend/dist release/
        tar -czf easytier-web-linux.tar.gz release/

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: easytier-web-linux
        path: easytier-web/easytier-web-linux.tar.gz
        retention-days: 5
