name: Build EasyTier-web

on:
  workflow_dispatch:  # 允许手动触发

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'pnpm'

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        components: rustfmt, clippy

    - name: Install Linux Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y pkg-config libssl-dev build-essential protobuf-compiler tree

    # 构建前端
    - name: Build Frontend
      run: |
        cd easytier-web
        echo "=== Installing dependencies ==="
        pnpm install
        
        echo "=== Building frontend-lib ==="
        cd frontend-lib
        pnpm build
        if [ ! -d "dist" ]; then
          echo "Error: frontend-lib dist directory not found!"
          exit 1
        fi
        
        echo "=== Building frontend ==="
        cd ../frontend
        pnpm build
        if [ ! -d "dist" ]; then
          echo "Error: frontend dist directory not found!"
          exit 1
        fi

    # 构建后端
    - name: Build Backend
      run: |
        cd easytier-web
        echo "=== Building backend ==="
        cargo build --release
        
        echo "=== Checking backend binary ==="
        BINARY_PATH="target/release/easytier-web"
        if [ ! -f "$BINARY_PATH" ]; then
          BINARY_PATH="target/release/easytier_web"
        fi
        
        if [ ! -f "$BINARY_PATH" ]; then
          echo "Error: Backend binary not found!"
          echo "=== Contents of target/release ==="
          ls -la target/release/
          exit 1
        fi

    # 打包
    - name: Package Build
      run: |
        cd easytier-web
        echo "=== Preparing release package ==="
        rm -rf release
        mkdir -p release
        
        echo "=== Copying backend binary ==="
        if [ -f "target/release/easytier-web" ]; then
          cp target/release/easytier-web release/
        elif [ -f "target/release/easytier_web" ]; then
          cp target/release/easytier_web release/easytier-web
        else
          echo "Error: Backend binary not found!"
          exit 1
        fi
        
        echo "=== Copying frontend files ==="
        if [ ! -d "frontend/dist" ]; then
          echo "Error: Frontend dist directory not found!"
          exit 1
        fi
        cp -r frontend/dist release/
        
        echo "=== Release directory contents ==="
        ls -la release/
        
        echo "=== Creating archive ==="
        tar -czvf easytier-web-linux.tar.gz release/

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: easytier-web-linux
        path: easytier-web/easytier-web-linux.tar.gz
        retention-days: 5
