name: Build EasyTier-web

on:
  workflow_dispatch:  # 允许手动触发

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'pnpm'

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable

    - name: Install Linux Dependencies
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y pkg-config libssl-dev

    - name: Build Frontend
      working-directory: ./easytier-web/frontend
      run: |
        pnpm install
        pnpm build

    - name: Build Frontend-lib
      working-directory: ./easytier-web/frontend-lib
      run: |
        pnpm install
        pnpm build

    - name: Build Backend
      working-directory: ./easytier-web
      run: |
        cargo build --release

    - name: Package Windows Build
      if: matrix.os == 'windows-latest'
      shell: pwsh
      run: |
        New-Item -ItemType Directory -Force -Path release
        Copy-Item "target\release\easytier-web.exe" -Destination "release\"
        Copy-Item -Recurse "frontend\dist" -Destination "release\dist"
        Compress-Archive -Path "release\*" -DestinationPath "easytier-web-windows.zip"

    - name: Package Linux Build
      if: matrix.os == 'ubuntu-latest'
      run: |
        mkdir -p release
        cp target/release/easytier-web release/
        cp -r frontend/dist release/
        tar -czf easytier-web-linux.tar.gz release/

    - name: Upload Windows Artifact
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v4
      with:
        name: easytier-web-windows
        path: easytier-web-windows.zip
        retention-days: 5

    - name: Upload Linux Artifact
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v4
      with:
        name: easytier-web-linux
        path: easytier-web-linux.tar.gz
        retention-days: 5
